### ISSUE TITLE
sha512 algo + "secret password" support

### ISSUE THREAD

**Issue by nordurljosahvida** [lanzz/bash-supergenpass#1]
Hi there. Thanks for the great work. Not really an issue, but how do you deal with sha256 in your script? Also, would you be interested in a slight addition which can handle "secret passwords" [also known as "salt" on the android app] as supported by the standard? [mainpassword:secretpassword]

Thanks

**Comment by nordurljosahvida** [comment]
Figured it out, it was sha512, updated title to reflect this, created pr https://github.com/lanzz/bash-supergenpass/pull/2 should you be interested. Thanks again for your great work!

**Comment by lanzz** [comment]
I don't agree with the "secret password" feature; it might make sense in a full app that can maintain actual secure storage for it (or hook into a system-wide secure storage), but in a shell script it pretty much amounts to keeping half of your password in plain text in the script file. There's no functional difference between storing the "secret" password in the script and actually typing it out at the end of the master password, thus you can easily maintain compatibility with the settings you use for the Android app without having an insecure implementation here.

If you amend your PR to exclude the secret password and only keep the default password length and the default algo I'll merge it 👍

**Comment by nordurljosahvida** [comment]
For me it’s also a “shoulder-surfing” issue, by which I mean that I’d like *not* to have to type in my full password in a public place, but then again the script on my computer is just a failsafe in case the android app were ever to completely stop working, I only use the android app on a phone that is dedicated to sgp and other security stuff, and it never exits airplane mode, so I totally agree with your point about security.

Anyways, I’ll amend the PR and get back to you.

Thanks

**Comment by lanzz** [comment]
PR merged 👍

**Comment by nordurljosahvida** [comment]
Awesome
