### ISSUE TITLE
I used your bash implementation to make a Perl and PHP version.

### ISSUE THREAD

**Issue by scottchiefbaker** [lanzz/bash-supergenpass#8]
Not really an issue, just wanted to let you know that I used your code as a base for my Perl and PHP implementations.

* [PHP](https://www.perturb.org/code/supergen_pass.php?domain=domain.com&amp;master=12345678) version
* [Perl](https://www.perturb.org/code/supergen_pass.pl) version

Go ahead and close this whenever you feel like. Happy Friday

**Comment by lanzz** [comment]
That's great! Happy Friday and happy holidays 😄
